[versions]
kotlin = "2.1.0"
compose-multiplatform = "1.7.0"
androidx-lifecycle = "2.8.4"
kotlinx-coroutines = "1.10.1"
javacpp = "1.5.10"
ktmidi = "0.10.1"

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
gradle-javacpp-platform = { id = "org.bytedeco.gradle-javacpp-platform", version.ref = "javacpp" }

[libraries]
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
ktmidi = { module = "dev.atsushieno:ktmidi", version.ref = "ktmidi" }
ktmidi-jvm-desktop = { module = "dev.atsushieno:ktmidi-jvm-desktop", version.ref = "ktmidi" }
